# Generated by Django 5.2.17 on 2026-09-29 06:05

import autoslug.fields
import django.db.models.deletion
import store.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheDealSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
                ('desc', models.CharField(max_length=1000, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('image1', models.ImageField(storage=store.supabase_storage.SupabaseStorage(bucket_name='product-images'), upload_to='products/')),
                ('image2', models.ImageField(storage=store.supabase_storage.SupabaseStorage(bucket_name='product-images'), upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, storage=store.supabase_storage.SupabaseStorage(bucket_name='product-images'), upload_to='products/')),
                ('image4', models.ImageField(blank=True, null=True, storage=store.supabase_storage.SupabaseStorage(bucket_name='product-images'), upload_to='products/')),
                ('video', models.FileField(blank=True, null=True, storage=store.supabase_storage.SupabaseStorage(bucket_name='product-videos'), upload_to='products/')),
                ('affilate_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sizevariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=5)),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirts.thedealspot')),
            ],
        ),
    ]
