# Generated by Django 5.2.17 on 2026-09-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0002_thedealspot_created_at_thedealspot_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thedealspot',
            name='affilate_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='thedealspot',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
